language: php

services:
  - memcached
  - redis-server

addons:
  hosts:
    - memcached-container
    - redis-container

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

script:
  - phpunit --stderr
